name: Build and push to another branch

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          SOCKET_URL: ${{ secrets.SOCKET_URL }}

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist/prod/public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
